version: '2'
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
#- "8000:8000" works on the local machine but not for aws    
      - "80:80"
    depends_on:
      - db
    links:
      - db:postgres
    volumes:
      - /var/www/html/sites
      - /var/www/private
    environment:
      - UPLOAD_LIMIT=20M
      - MEMORY_LIMIT=128M
      - VIRTUAL_HOST=foo.bar.zap
      - BASE_URL_PROTO=http://

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data
