# This is a sample configuration to run a Drupal-instance with Docker-Compose.
# For customization options see: https://docs.docker.com/compose/yml/

web:
  image: carolodiornebi/drupal:8.x
  links:
    - db:postgres
  volumes:
    - /var/www/html/sites
    - /var/www/private
  environment:
    - UPLOAD_LIMIT=20M
    - MEMORY_LIMIT=128M
    - VIRTUAL_HOST=foo.bar.zap

db:
  image: postgres
  environment:
#    - MYSQL_ROOT_PASSWORD=password
    - PGPASSWORD=mysecretpassword
  volumes:
    - /var/lib/postgres
